# Generated by Django 3.1 on 2020-08-18 23:20

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('degree', models.CharField(max_length=100)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('institution', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('image', models.ImageField(upload_to='experiences')),
                ('title', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('content', ckeditor.fields.RichTextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('dateUpdated', models.DateTimeField(auto_now=True)),
                ('dateAdded', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=100)),
                ('summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('webType', models.CharField(max_length=10)),
                ('portfolioPageHeader', models.TextField()),
                ('experiencePageHeader', models.TextField()),
                ('educationPageHeader', models.TextField()),
                ('contactPageHeader', models.TextField()),
                ('email', models.EmailField(default='jiachengzhang1@email.arizona.edu', max_length=254)),
                ('github', models.URLField(default='https://github.com/jiachengzhang1')),
                ('linkedIn', models.URLField(default='www.linkedin.com/in/jiachengzhang-developer')),
                ('resumeLink', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('content', ckeditor.fields.RichTextField()),
                ('demoURL', models.URLField(blank=True, null=True)),
                ('codeURL', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects')),
                ('date', models.DateField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('technologies', models.ManyToManyField(related_name='project', to='portfolio_web.Technology')),
            ],
        ),
    ]
