# Generated by Django 3.1 on 2020-08-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteinfo',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='web'),
        ),
    ]
