# Generated by Django 3.1 on 2020-08-14 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_web', '0002_remove_technology_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
