# Generated by Django 3.1 on 2020-08-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_web', '0003_auto_20200816_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='priority',
            field=models.IntegerField(),
        ),
    ]
