# Generated by Django 3.1 on 2020-08-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_web', '0004_auto_20200814_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(related_name='project', to='portfolio_web.Technology'),
        ),
    ]
