# Generated by Django 3.1 on 2020-08-15 00:15

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_web', '0005_auto_20200815_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
