# Generated by Django 3.1 on 2020-08-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_web', '0006_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('webType', models.CharField(max_length=10)),
            ],
        ),
    ]
