# Generated by Django 3.1 on 2020-08-15 22:11

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_web', '0007_auto_20200815_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='experiences')),
                ('title', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('content', ckeditor.fields.RichTextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('dateUpdated', models.DateTimeField(auto_now=True)),
                ('dateAdded', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='codeURL',
            field=models.URLField(default='tmp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='demoURL',
            field=models.URLField(default='tmp'),
            preserve_default=False,
        ),
    ]
