# Generated by Django 3.1 on 2020-08-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_web', '0007_websiteinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteinfo',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
