# Generated by Django 3.1 on 2020-08-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_web', '0008_auto_20200818_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteinfo',
            name='title',
            field=models.CharField(default='Software Developer', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='websiteinfo',
            name='url',
            field=models.URLField(default='http://jzhangdeveloper.com'),
            preserve_default=False,
        ),
    ]
