# Generated by Django 3.1 on 2020-08-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_web', '0009_auto_20200818_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteinfo',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
