# Generated by Django 3.1 on 2020-08-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_web', '0010_auto_20200818_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteinfo',
            name='contactPageHeader',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websiteinfo',
            name='educationPageHeader',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websiteinfo',
            name='experiencePageHeader',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websiteinfo',
            name='portfolioPageHeader',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
    ]
