# Generated by Django 3.1 on 2020-08-18 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_web', '0011_auto_20200818_2142'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebsiteInfo',
        ),
    ]
