# Generated by Django 3.1 on 2020-08-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_web', '0013_websiteinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteinfo',
            name='url',
            field=models.URLField(default='1'),
            preserve_default=False,
        ),
    ]
