language: python

python:
  - "3.8"

services: postgresql

env:
  global:
    - DJANGO_SETTINGS_MODULE="portfolio.settings"
    - PYTHONPATH="/home/travis/build/jiachengzhang1/portfolio-web"
    - PIP_USE_MIRRORS=true
    - BUILD_ON_TRAVIS=true
  matrix:
    - DJANGO=3.1 DB=postgresql

#commands to install dependencies
install:
  - pip install -q -r requirements.txt

#command to run the test suite
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test
